### PR TITLE
6.5: EEVDF adaptation to BORE 3.2.8

### PR DESCRIPTION
**Pull request by sirlucjan**
Necessary patches to support BORE 3.2.8: https://github.com/firelzrd/bore-scheduler/commits/main

Source: https://git.kernel.org/pub/scm/linux/kernel/git/peterz/queue.git/log/?h=sched/eevdf

### CODE REVIEW

**Comment by Tk-Glitch** [comment]
Thanks sirlucjan! :frog: :heart:

**Comment by sirlucjan** [comment]
You're welcome.

**Comment by ptr1337** [comment]
@sirlucjan will push the needed bore patches in a few minutes into CachyOS kernel-patches repo.

**Comment by sirlucjan** [comment]
Done, repo updated

**Pull request merged**
