### PR TITLE
fix Frogging-Family#347

### LINKED ISSUE #347: Fix for Frogging-Family#340 breaks build on 5.14.17
The fix for #340 (725dd102b8fceff44c5d1619a2aad61c72446f65) breaks the build on 5.14.17 (patch is failing to apply).  The upstream issue suggests that the bug has been fixed: https://bugzilla.kernel.org/show_bug.cgi?id=214859#c7

I'm able to build and boot with the patch removed but I'm not on a Ryzen APU so I'm not 100% sure if removing the patch is the right move and/or if the original issue is fixed. Will open a PR with my changes for review shortly.

<details>
<summary>prepare.log</summary>

```
### Applying 0001-add-sysctl-to-disallow-unprivileged-CLONE_NEWUSER-by.patch... ###
patching file kernel/fork.c
Hunk #1 succeeded at 108 (offset 6 lines).
Hunk #2 succeeded at 1882 (offset 322 lines).
Hunk #3 succeeded at 2990 (offset 633 lines).
patching file kernel/sysctl.c
Hunk #1 succeeded at 108 (offset 3 lines).
Hunk #2 succeeded at 1911 (offset 1395 lines).
patching file kernel/user_namespace.c
Hunk #1 succeeded at 21 with fuzz 2 (offset -3 lines).
patching file init/Kconfig
Hunk #1 succeeded at 1198 (offset 194 lines).
patching file kernel/user_namespace.c
Hunk #1 succeeded at 22 (offset -5 lines).


### Applying more-uarches-for-kernel-5.8-5.14.patch... ###
patching file arch/x86/Kconfig.cpu
patching file arch/x86/Makefile
Hunk #1 succeeded at 122 (offset 8 lines).
patching file arch/x86/include/asm/vermagic.h


### Applying 0002-clear-patches.patch... ###
patching file drivers/pci/pci.c
Hunk #1 succeeded at 59 (offset -3 lines).
patching file drivers/idle/intel_idle.c
Hunk #1 succeeded at 502 (offset -29 lines).
Hunk #2 succeeded at 510 (offset -29 lines).
Hunk #3 succeeded at 518 (offset -29 lines).
Hunk #4 succeeded at 526 (offset -29 lines).
Hunk #5 succeeded at 534 (offset -29 lines).
Hunk #6 succeeded at 542 (offset -29 lines).
Hunk #7 succeeded at 550 (offset -29 lines).
Hunk #8 succeeded at 570 (offset -29 lines).
Hunk #9 succeeded at 578 (offset -29 lines).
Hunk #10 succeeded at 586 (offset -29 lines).
Hunk #11 succeeded at 594 (offset -29 lines).
Hunk #12 succeeded at 602 (offset -29 lines).
Hunk #13 succeeded at 610 (offset -29 lines).
Hunk #14 succeeded at 618 (offset -29 lines).
Hunk #15 succeeded at 639 (offset -29 lines).
Hunk #16 succeeded at 647 (offset -29 lines).
Hunk #17 succeeded at 655 (offset -29 lines).
Hunk #18 succeeded at 663 (offset -29 lines).
Hunk #19 succeeded at 671 (offset -29 lines).
Hunk #20 succeeded at 679 (offset -29 lines).
Hunk #21 succeeded at 687 (offset -29 lines).
Hunk #22 succeeded at 708 (offset -29 lines).
patching file net/ipv4/tcp.c
Hunk #1 succeeded at 4557 (offset 356 lines).
patching file kernel/locking/rwsem.c
Hunk #1 succeeded at 668 with fuzz 1 (offset -49 lines).
Hunk #2 succeeded at 702 (offset -49 lines).
patching file drivers/Makefile
Hunk #1 succeeded at 60 (offset 1 line).
Hunk #2 succeeded at 74 (offset 1 line).


### Applying 0003-glitched-base.patch... ###
patching file scripts/mkcompile_h
Hunk #1 succeeded at 39 (offset -2 lines).
patching file fs/dcache.c
patching file kernel/sched/core.c
Hunk #1 succeeded at 74 (offset 15 lines).
Hunk #2 succeeded at 366 with fuzz 2 (offset 295 lines).
patching file scripts/setlocalversion
patching file init/Kconfig
Hunk #1 succeeded at 1353 (offset 75 lines).
patching file drivers/infiniband/core/addr.c
Hunk #1 succeeded at 821 (offset 1 line).
patching file init/Kconfig
Hunk #1 succeeded at 107 (offset 15 lines).
patching file kernel/sched/fair.c
Hunk #1 succeeded at 35 (offset -2 lines).
Hunk #2 succeeded at 61 (offset -2 lines).
Hunk #3 succeeded at 147 (offset 5 lines).
patching file mm/page-writeback.c
Hunk #1 succeeded at 70 (offset -1 lines).
Hunk #2 succeeded at 91 (offset -1 lines).
patching file net/ipv4/Kconfig
patching file mm/huge_memory.c
Hunk #1 succeeded at 54 (offset 1 line).
patching file net/sched/Kconfig
Hunk #1 succeeded at 474 (offset 3 lines).
Hunk #2 succeeded at 488 with fuzz 2 (offset 4 lines).
patching file mm/page_alloc.c
Hunk #1 succeeded at 339 (offset 9 lines).
patching file include/linux/mm.h
Hunk #1 succeeded at 198 (offset 8 lines).
patching file include/linux/mm.h
Hunk #1 succeeded at 198 (offset 8 lines).
patching file block/elevator.c
Hunk #1 succeeded at 628 (offset 5 lines).
patching file include/linux/pagemap.h
Hunk #1 succeeded at 852 with fuzz 2 (offset 197 lines).
patching file Documentation/admin-guide/kernel-parameters.txt
Hunk #1 succeeded at 1974 (offset 117 lines).
patching file drivers/cpufreq/intel_pstate.c
Hunk #1 succeeded at 3367 (offset 522 lines).


### Applying 0012-misc-additions.patch... ###
patching file drivers/hid/hid-quirks.c
Hunk #1 succeeded at 481 (offset 3 lines).
patching file drivers/gpu/drm/amd/amdgpu/amdgpu_drv.c
Hunk #1 succeeded at 215 (offset 23 lines).
patching file drivers/gpu/drm/amd/amdgpu/amdgpu_ttm.c
Hunk #1 succeeded at 1738 (offset -127 lines).
patching file drivers/cpufreq/Kconfig
Hunk #1 succeeded at 72 (offset 1 line).
Hunk #2 succeeded at 84 (offset 2 lines).
patching file arch/x86/kernel/acpi/cstate.c
patching file drivers/gpu/drm/amd/amdgpu/amdgpu_device.c
Hunk #2 FAILED at 2388.
1 out of 2 hunks FAILED -- saving rejects to file drivers/gpu/drm/amd/amdgpu/amdgpu_device.c.rej
patching file drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c
Hunk #1 succeeded at 4758 (offset -294 lines).
patching file drivers/gpu/drm/amd/display/dc/core/dc.c
Hunk #1 succeeded at 1971 (offset -44 lines).
patching file drivers/gpu/drm/amd/display/dc/dcn30/dcn30_hubp.c
patching file drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c
Hunk #1 succeeded at 4759 (offset -294 lines).
patching file drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c
Hunk #1 succeeded at 4673 (offset -282 lines).
Hunk #2 succeeded at 4700 with fuzz 2 (offset -277 lines).


### Applying 0001-mm-Support-soft-dirty-flag-reset-for-VA-range.patch... ###
patching file fs/proc/task_mmu.c
Hunk #1 succeeded at 1031 (offset -1 lines).
Hunk #2 succeeded at 1124 (offset -3 lines).
Hunk #3 succeeded at 1182 (offset -3 lines).
Hunk #4 succeeded at 1209 (offset -3 lines).
Hunk #5 succeeded at 1223 (offset -3 lines).
Hunk #6 succeeded at 1262 (offset -3 lines).
Hunk #7 succeeded at 1374 (offset -3 lines).
Hunk #8 succeeded at 1448 (offset -2 lines).
Hunk #9 succeeded at 1500 (offset -77 lines).
Hunk #10 succeeded at 1520 (offset 1 line).


### Applying 0002-mm-Support-soft-dirty-flag-read-with-reset.patch... ###
patching file fs/proc/base.c
Hunk #1 succeeded at 3214 (offset 12 lines).
patching file fs/proc/internal.h
Hunk #1 succeeded at 305 (offset 2 lines).
patching file fs/proc/task_mmu.c
Hunk #1 succeeded at 1053 (offset -3 lines).
Hunk #2 succeeded at 1063 (offset -3 lines).
Hunk #3 succeeded at 1113 (offset -3 lines).
Hunk #4 succeeded at 1376 (offset -3 lines).
Hunk #5 succeeded at 1409 (offset -2 lines).
Hunk #6 succeeded at 1424 (offset -2 lines).
Hunk #7 succeeded at 1461 (offset -2 lines).
Hunk #8 succeeded at 1517 (offset -1 lines).
Hunk #9 succeeded at 1583 (offset 3 lines).
Hunk #10 succeeded at 1598 (offset 3 lines).
Hunk #11 succeeded at 1701 (offset 3 lines).
Hunk #12 succeeded at 1711 (offset 3 lines).
Hunk #13 succeeded at 1728 (offset 3 lines).
Hunk #14 succeeded at 1779 (offset 3 lines).
Hunk #15 succeeded at 1815 (offset 3 lines).
Hunk #16 succeeded at 1830 (offset 3 lines).
Hunk #17 succeeded at 1868 (offset 3 lines).


### Applying 0009-prjc_v5.14-r3.patch... ###
patching file Documentation/admin-guide/kernel-parameters.txt
Hunk #1 succeeded at 4950 (offset 3 lines).
patching file Documentation/admin-guide/sysctl/kernel.rst
patching file Documentation/scheduler/sched-BMQ.txt
patching file fs/proc/base.c
patching file include/asm-generic/resource.h
patching file include/linux/sched.h
Hunk #5 succeeded at 1440 (offset 1 line).
patching file include/linux/sched/deadline.h
patching file include/linux/sched/prio.h
patching file include/linux/sched/rt.h
patching file include/linux/sched/topology.h
patching file init/Kconfig
Hunk #1 succeeded at 818 (offset 32 lines).
Hunk #2 succeeded at 936 (offset 32 lines).
Hunk #3 succeeded at 1029 (offset 32 lines).
Hunk #4 succeeded at 1052 (offset 32 lines).
Hunk #5 succeeded at 1312 (offset 48 lines).
patching file init/init_task.c
patching file kernel/Kconfig.preempt
patching file kernel/cgroup/cpuset.c
patching file kernel/delayacct.c
patching file kernel/exit.c
patching file kernel/livepatch/transition.c
patching file kernel/locking/rtmutex.c
patching file kernel/sched/Makefile
patching file kernel/sched/alt_core.c
patching file kernel/sched/alt_debug.c
patching file kernel/sched/alt_sched.h
patching file kernel/sched/bmq.h
patching file kernel/sched/cpufreq_schedutil.c
Hunk #3 succeeded at 614 (offset 8 lines).
Hunk #4 succeeded at 847 (offset 6 lines).
patching file kernel/sched/cputime.c
patching file kernel/sched/debug.c
Hunk #2 succeeded at 217 (offset 6 lines).
Hunk #3 succeeded at 281 (offset 6 lines).
Hunk #4 succeeded at 297 (offset 6 lines).
Hunk #5 succeeded at 307 (offset 6 lines).
Hunk #6 succeeded at 343 (offset 6 lines).
Hunk #7 succeeded at 1069 (offset 13 lines).
patching file kernel/sched/idle.c
patching file kernel/sched/pds.h
patching file kernel/sched/pelt.c
patching file kernel/sched/pelt.h
patching file kernel/sched/sched.h
Hunk #2 succeeded at 3044 (offset 2 lines).
patching file kernel/sched/stats.c
patching file kernel/sched/topology.c
Hunk #3 succeeded at 1622 (offset 2 lines).
Hunk #4 succeeded at 1652 (offset 2 lines).
Hunk #5 succeeded at 2521 (offset 65 lines).
patching file kernel/sysctl.c
Hunk #1 succeeded at 125 (offset 3 lines).
Hunk #2 succeeded at 1737 (offset 3 lines).
Hunk #3 succeeded at 1885 (offset 3 lines).
Hunk #4 succeeded at 2471 (offset 12 lines).
patching file kernel/time/hrtimer.c
Hunk #1 succeeded at 1986 (offset 46 lines).
patching file kernel/time/posix-cpu-timers.c
patching file kernel/trace/trace_selftest.c


### Applying 0009-glitched-ondemand-bmq.patch... ###
patching file drivers/cpufreq/cpufreq_ondemand.c
Hunk #1 succeeded at 18 (offset -3 lines).


### Applying 0009-glitched-bmq.patch... ###
patching file kernel/Kconfig.hz
Hunk #1 succeeded at 5 (offset 1 line).
Hunk #2 succeeded at 40 (offset 1 line).
Hunk #3 succeeded at 60 (offset 1 line).
patching file kernel/Kconfig.hz
Hunk #1 succeeded at 5 (offset 1 line).
Hunk #2 succeeded at 47 (offset 1 line).
Hunk #3 succeeded at 68 (offset 1 line).
patching file mm/vmscan.c
Hunk #1 succeeded at 170 (offset 1 line).


### Applying 0007-v5.14-fsync.patch... ###
patching file include/uapi/linux/futex.h
Hunk #1 succeeded at 22 (offset 1 line).
Hunk #2 succeeded at 43 (offset 2 lines).
Hunk #3 succeeded at 155 (offset 2 lines).
patching file kernel/futex.c
Hunk #3 succeeded at 2317 with fuzz 2 (offset -3 lines).
Hunk #4 succeeded at 2703 (offset -3 lines).
Hunk #5 succeeded at 3992 with fuzz 1 (offset 3 lines).
Hunk #6 succeeded at 4012 (offset 3 lines).
Hunk #7 succeeded at 4069 (offset 3 lines).
Hunk #8 succeeded at 4250 (offset 3 lines).
Hunk #9 succeeded at 4318 (offset 3 lines).
patching file include/uapi/linux/futex.h
Hunk #1 succeeded at 22 (offset 1 line).
patching file kernel/futex.c
Hunk #1 succeeded at 4005 (offset 3 lines).
Hunk #2 succeeded at 4258 (offset 3 lines).


### Applying 0007-v5.14-futex2_interface.patch... ###
patching file MAINTAINERS
Hunk #1 succeeded at 7660 (offset 139 lines).
patching file arch/arm/tools/syscall.tbl
patching file arch/arm64/include/asm/unistd.h
patching file arch/arm64/include/asm/unistd32.h
Hunk #1 succeeded at 901 (offset 1 line).
patching file arch/x86/entry/syscalls/syscall_32.tbl
Hunk #1 succeeded at 452 (offset 1 line).
patching file arch/x86/entry/syscalls/syscall_64.tbl
Hunk #1 succeeded at 369 (offset 1 line).
patching file include/linux/syscalls.h
patching file include/uapi/asm-generic/unistd.h
Hunk #1 succeeded at 878 (offset 5 lines).
patching file include/uapi/linux/futex.h
Hunk #1 succeeded at 46 with fuzz 1 (offset 5 lines).
patching file init/Kconfig
Hunk #1 succeeded at 1639 (offset 84 lines).
patching file kernel/Makefile
patching file kernel/futex2.c
patching file kernel/sys_ni.c
patching file tools/include/uapi/asm-generic/unistd.h
Hunk #1 succeeded at 878 (offset 5 lines).
patching file tools/perf/arch/x86/entry/syscalls/syscall_64.tbl
Hunk #1 succeeded at 369 (offset 1 line).
patching file fs/inode.c
patching file include/linux/fs.h
patching file include/uapi/linux/futex.h
Hunk #1 succeeded at 51 (offset 5 lines).
patching file kernel/futex2.c
patching file arch/arm/tools/syscall.tbl
patching file arch/arm64/include/asm/unistd.h
patching file arch/x86/entry/syscalls/syscall_32.tbl
Hunk #1 succeeded at 454 with fuzz 1 (offset 1 line).
patching file arch/x86/entry/syscalls/syscall_64.tbl
Hunk #1 succeeded at 371 (offset 1 line).
patching file include/linux/compat.h
Hunk #2 succeeded at 696 (offset -2 lines).
patching file include/linux/syscalls.h
patching file include/uapi/asm-generic/unistd.h
Hunk #1 succeeded at 884 (offset 5 lines).
patching file include/uapi/linux/futex.h
Hunk #1 succeeded at 53 (offset 5 lines).
patching file kernel/futex2.c
patching file kernel/sys_ni.c
patching file tools/include/uapi/asm-generic/unistd.h
Hunk #1 succeeded at 884 (offset 5 lines).
patching file tools/perf/arch/x86/entry/syscalls/syscall_64.tbl
Hunk #1 succeeded at 371 (offset 1 line).
patching file arch/arm/tools/syscall.tbl
patching file arch/arm64/include/asm/unistd.h
patching file arch/x86/entry/syscalls/syscall_32.tbl
Hunk #1 succeeded at 455 (offset 1 line).
patching file arch/x86/entry/syscalls/syscall_64.tbl
Hunk #1 succeeded at 372 (offset 1 line).
patching file include/linux/compat.h
Hunk #2 succeeded at 706 (offset -2 lines).
patching file include/linux/syscalls.h
patching file include/uapi/asm-generic/unistd.h
Hunk #1 succeeded at 887 (offset 5 lines).
patching file include/uapi/linux/futex.h
Hunk #1 succeeded at 67 (offset 5 lines).
patching file kernel/futex2.c
patching file kernel/sys_ni.c
patching file kernel/futex2.c
patching file Documentation/locking/futex2.rst
patching file Documentation/locking/index.rst
patching file tools/testing/selftests/futex/functional/.gitignore
Hunk #1 succeeded at 8 (offset 2 lines).
patching file tools/testing/selftests/futex/functional/Makefile
Hunk #1 succeeded at 6 (offset 5 lines).
Hunk #2 succeeded at 18 (offset 3 lines).
patching file tools/testing/selftests/futex/functional/futex2_wait.c
patching file tools/testing/selftests/futex/functional/run.sh
Hunk #1 succeeded at 79 (offset 6 lines).
patching file tools/testing/selftests/futex/include/futex2test.h
patching file tools/testing/selftests/futex/functional/futex_wait_timeout.c
patching file tools/testing/selftests/futex/functional/futex_wait_wouldblock.c
patching file tools/testing/selftests/futex/functional/.gitignore
Hunk #1 succeeded at 9 with fuzz 2 (offset 2 lines).
patching file tools/testing/selftests/futex/functional/Makefile
Hunk #1 succeeded at 19 (offset 3 lines).
patching file tools/testing/selftests/futex/functional/futex2_waitv.c
patching file tools/testing/selftests/futex/functional/run.sh
Hunk #1 succeeded at 82 (offset 6 lines).
patching file tools/testing/selftests/futex/include/futex2test.h
patching file tools/testing/selftests/futex/functional/.gitignore
Hunk #1 succeeded at 10 with fuzz 1 (offset 2 lines).
patching file tools/testing/selftests/futex/functional/Makefile
Hunk #1 succeeded at 20 (offset 3 lines).
patching file tools/testing/selftests/futex/functional/futex2_requeue.c
patching file tools/testing/selftests/futex/include/futex2test.h
patching file tools/arch/x86/include/asm/unistd_64.h
patching file tools/perf/bench/bench.h
patching file tools/perf/bench/futex-hash.c
patching file tools/perf/bench/futex-requeue.c
patching file tools/perf/bench/futex-wake-parallel.c
patching file tools/perf/bench/futex-wake.c
patching file tools/perf/bench/futex.h
patching file tools/perf/builtin-bench.c
patching file include/linux/syscalls.h
Hunk #1 succeeded at 1326 (offset 1 line).
patching file kernel/fork.c
Hunk #1 succeeded at 1333 (offset 11 lines).
patching file kernel/futex2.c
patching file kernel/futex2.c


linux-tkg user patches, if any:
```

</details>

### PR DESCRIPTION
**Pull request by itspngu**
Fixes #347. This is my first PR and I'm not used to hacking on the kernel so if there's anything wrong, please gently nudge me in the right direction :)

### CODE REVIEW

**Comment by AdelKS** [comment]
Hello! Looks good to me. You confirmed the patch applies and resulting kernel works ?

**Comment by itspngu** [comment]
> You confirmed the patch applies and resulting kernel works ?

Well, I removed the patch to fix the build. The resulting kernel works, I'm on it right now. I'm just not sure if the actual problem was fixed upstream, as outlined in the issue I created prior to opening this PR: https://github.com/Frogging-Family/linux-tkg/issues/347

**Comment by Tk-Glitch** [comment]
I totally forgot to do it with the PR bumping versions and all. Thanks! :frog: :heart:

**Comment by AdelKS** [comment]
Haha me too, I had quickly read about the issue and forgot about it

**Pull request merged**
