### PR TITLE
update bcachefs for 5.18, add bcachefs for 5.19, include module-fix

### PR DESCRIPTION
**Pull request by ptr1337**
- Update bcachefs for 5.18
- Add bcachefs for 5.19
- Include module compilation fix, but still recommend to built it with =y right now
 
Signed-off-by: Peter Jung <admin@ptr1337.dev>

### CODE REVIEW

**Comment by Tk-Glitch** [comment]
That's for non-MGLRU, right?

**Comment by ptr1337** [comment]
> That's for non-MGLRU, right?

Yes. I have for MG-LRU in my kernel-patches repo. If you want I can add the patches also here and update them every 4 weeks or something like this ?

You can find them here:
5.18: https://github.com/ptr1337/kernel-patches/blob/master/5.18/misc/0001-bcachefs-after-lru.patch
5.19: https://github.com/ptr1337/kernel-patches/blob/master/5.19/0001-bcachefs-after-lru.patch

**Comment by Tk-Glitch** [comment]
There are plans for offering mglru by default soon-ish, so that shouldn't be a problem for long. Thank you ptr1337! 
:frog: :heart:

**Comment by ptr1337** [comment]
> There are plans for offering mglru by default soon-ish, so that shouldn't be a problem for long. Thank you ptr1337! frog heart

Would recommend it anyways. It is really well tested over the latest kernel versions and will be maybe merged with 5.20 anyways (so far there seems nothing to be in linux-next). 

Just a little entry in the customization.cfg to enabled by default or not, so it can be patched all time in and also then enabled manually if the user not used to enable it as default.

**Pull request merged**
