### PR TITLE
Update README for 5.10 (not rc anymore), 5.11 and futex2

### PR DESCRIPTION
**Pull request by ninelore**

### CODE REVIEW

**Comment by ninelore** [comment]
I just saw the other, older PR. Idk what the status of that.

**Comment by Tk-Glitch** [comment]
> Idk what the status of that.

It's not ready imo.

Thank you! :frog: :heart:

**Comment by ninelore** [comment]
np

**Comment by AdelKS** [comment]
Even if you still deem it not ready, I'm still waiting for that feedback! 😭

I do think it's better than the current readme, though. I have to give it a re-read 🤔

**Pull request merged**
