### PR TITLE
Update to Project C 5.8-r2

### PR DESCRIPTION
**Pull request by Edu4rdSHL**
- Ref: https://cchalpha.blogspot.com/2020/09/project-c-v58-r2-release.html

### CODE REVIEW

**Comment by openglfreak** [comment]
PDS is back! Nice!

**Comment by Tk-Glitch** [comment]
Looks fine to me! Thanks. I'll check the new PDS implementation out to replace ours soon.

**Comment by AdelKS** [comment]
I was waiting for zis for so long! Finally! Let's give it a try now :D

**Comment by JDC2389** [comment]
> I was waiting for zis for so long! Finally! Let's give it a try now :D

It's not building atm needs more commit fixies

**Comment by AdelKS** [comment]
Is it [this issue](https://gitlab.com/alfredchen/linux-prjc/-/issues/10) ? It seems to have been fixed before this merge ? :thinking:

**Comment by JDC2389** [comment]
> Is it [this issue](https://gitlab.com/alfredchen/linux-prjc/-/issues/10) ? It seems to have been fixed (chronologically) before this merge ?

nope it has a yet to be fixed separate issue, everyone has listed logs already it should get sorted at some point soon I think

**Pull request merged**
