### PR TITLE
add ebuild

### PR DESCRIPTION
**Pull request by qwe795138426**

### CODE REVIEW

**Comment by Tk-Glitch** [comment]
wth

**Comment by itspngu** [comment]
0 commits :monocle_face:

**Comment by Snoop05** [comment]
delet dis, install windows xp instead :joy:

**Comment by AdelKS** [comment]
Ebuilds cannot bundle the flexibility of linux-tkg. These are missing the entirety of the `.config` tweaks. Also, one can install only one kernel 5.x version at a time. Although it may be suitable for some Gentoo users.

**Comment by qwe795138426** [comment]
oh, bot forced pulled and covered my change

**Comment by qwe795138426** [comment]
> Ebuilds cannot bundle the flexibility of linux-tkg. These are missing the entirety of the `.config` tweaks. Also, one can install only one kernel 5.x version at a time. Although it may be suitable for some Gentoo users.

Of course, I don't think a full `.config` is necessary because I think most of Gentoo users are more likely to decide their config by themselves. 

Through USE, it might be not influence its flexibility. To people in need, applying patches by themselves rather than use a pre-configured sources maybe more suitable.

If you like, I can add `.config` as defconfig to deal with it.

**Comment by qwe795138426** [comment]
Let me try once more.

**Pull request merged**
