### PR TITLE
Add _kernel_on_diet customization option

### PR DESCRIPTION
**Pull request by AdelKS**
Hello,

2023 is the year linux-tkg decided to be more wary of its weight and start exercising.

So, this PR adds `_kernel_on_diet` option, that makes use of a bundled-in `minimal-modprobed.db` file to build the kernel. I think the db is still not as big as it should be, but we will keep growing it with everyone's contribution of their db. Then we can count on issues/PRs to add more modules to the list.

This change is motivated by the need to fix github ci built kernels, which stopped to successfully build after kernels got too fat or github lowered the specs of their runners, who knows. I activated this setting in the ci on the master branch of my fork, let's see if it successfully builds.

### CODE REVIEW

**Comment by Tk-Glitch** [comment]
Looks like it worked !
#404 for the win !
Thanks Adel, as always <3

**Comment by ryanmusante** [comment]
Interesting, what happens when you compile with a smaller kernel and it needs additional modules? Will it just error out on the ones that were extricated?

**Comment by Tk-Glitch** [comment]
Well, the module won't exist in the package so the app or hardware depending on it will not work. The idea is to make this grow to cover 99% of users needs.

**Comment by ryanmusante** [comment]
OK, I'll build with modprobed.db next time and contribute. I'm running on a fairly typical laptop install.

**Comment by ryanmusante** [comment]
[modprobed.db.txt](https://github.com/Frogging-Family/linux-tkg/files/12554801/modprobed.db.txt)

**Pull request merged**
