### PR TITLE
Fix GraySky2 patch link from Install.sh

### PR DESCRIPTION
**Pull request by iWeaker4you**

### CODE REVIEW

**Comment by AdelKS** [comment]
@Tk-Glitch you forgot about the poor `install.sh` users in your d2cc04e commit :disappointed:

**Comment by Tk-Glitch** [comment]
As I do most of the time :frog:

**Comment by Tk-Glitch** [comment]
Thanks @iWeaker4you :frog: :heart:

**Comment by AdelKS** [comment]
Well, it is true that I am (implicitly) supposed to take care of that x) I will be soon more up to date with `install.sh` because I will start using it regularly for my brand new beloved distro xD

**Pull request merged**
