### PR TITLE
Add schedtool pacakge for fedora

### PR DESCRIPTION
**Pull request by arvdl**
Missing the package 'schedtool' on Fedora Linux.
Tested on Fedora 34

### CODE REVIEW

**Comment by AdelKS** [comment]
Hello,

Good idea! Can you add for the other Fedora versions, Suze, Debian and Ubuntu ? The package name is the same for all of them.

Thanks!

**Comment by arvdl** [comment]
Added the schedtool for all distros

**Comment by AdelKS** [comment]
Awesome thanks! Now everyone can enjoy a responsive system while compiling.

**Comment by AdelKS** [comment]
Please rebase the change so it can get merged :D

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/linux-tkg/commit/10f242d4216bfb43eadbc4c11c47cb88f51af93d

**Pull request closed without merging**
