### PR TITLE
6.5: Add new EEVDF patches for BORE 3.2.0 (fix #825)

### LINKED ISSUE #825: Error applying BORE-EEVDF on kernel 6.5.7
Relevant snip from prepare.log.txt:
```
### Applying 0001-bore-eevdf.patch... ###
patching file include/linux/sched.h
Hunk #3 succeeded at 1013 (offset -1 lines).
patching file init/Kconfig
Hunk #1 succeeded at 1306 (offset 28 lines).
patching file kernel/sched/core.c
Hunk #1 succeeded at 4485 (offset -6 lines).
Hunk #2 succeeded at 4653 with fuzz 2 (offset -6 lines).
Hunk #3 succeeded at 4975 (offset -8 lines).
Hunk #4 succeeded at 10081 (offset -31 lines).
patching file kernel/sched/debug.c
patching file kernel/sched/fair.c
Hunk #5 FAILED at 817.
Hunk #6 succeeded at 829 with fuzz 2 (offset -8 lines).
Hunk #7 succeeded at 858 (offset -8 lines).
Hunk #8 succeeded at 1274 (offset -60 lines).
Hunk #9 FAILED at 5137.
Hunk #10 succeeded at 5156 (offset -63 lines).
Hunk #11 succeeded at 6638 (offset -63 lines).
Hunk #12 succeeded at 8365 (offset -63 lines).
Hunk #13 succeeded at 8379 (offset -63 lines).
2 out of 13 hunks FAILED -- saving rejects to file kernel/sched/fair.c.rej
patching file kernel/sched/features.h
```
Trying to build on default customization.cfg, Fedora 39

### PR DESCRIPTION
**Pull request by sirlucjan**
Adding these 4 patches should fix the above mentioned error (#825)

### CODE REVIEW

**Comment by v1993** [comment]
Can confirm that this fixes the build error, although I'd like to be sure that issues that prompted switch from your version of bore-eevdf in #820 were addressed. Also, this probably should change `linux-tkg-config/prepare` file accordingly?

**Comment by Tk-Glitch** [comment]
Thanks sirlucjan! :frog: :heart:

**Comment by sirlucjan** [comment]
You're welcome!

**Comment by John-Dekka** [comment]
Breaks compiling linux-tkg for me with 6) BORE (Burst-Oriented Response Enhancer - EEVDF variant) CPU Scheduler


-> Applying BORE-EEVDF patch
==> ERROR: An error was encountered applying patches. It was logged to the prepare.log.txt file.

 
### Applying 0001-bore-eevdf.patch... ###
patching file include/linux/sched.h
Hunk #2 succeeded at 580 (offset 3 lines).
Hunk #3 succeeded at 1017 (offset 3 lines).
patching file init/Kconfig
Hunk #1 succeeded at 1306 (offset 28 lines).
patching file kernel/sched/core.c
Hunk #1 succeeded at 4496 (offset 5 lines).
Hunk #2 succeeded at 4664 (offset 5 lines).
Hunk #3 succeeded at 4987 (offset 4 lines).
Hunk #4 succeeded at 10155 (offset 43 lines).
patching file kernel/sched/debug.c
Hunk #1 succeeded at 595 (offset 1 line).
patching file kernel/sched/fair.c
Hunk #2 succeeded at 69 with fuzz 2.
Hunk #3 succeeded at 94 (offset -6 lines).
Hunk #4 FAILED at 219.
Hunk #5 succeeded at 374 (offset -13 lines).
Hunk #6 succeeded at 779 (offset -13 lines).
Hunk #7 succeeded at 1244 (offset -18 lines).
Hunk #8 succeeded at 6643 (offset 20 lines).
Hunk #9 succeeded at 8385 (offset 35 lines).
Hunk #10 succeeded at 8399 (offset 35 lines).
1 out of 10 hunks FAILED -- saving rejects to file kernel/sched/fair.c.rej
patching file kernel/sched/features.h
Hunk #1 FAILED at 6.
1 out of 1 hunk FAILED -- saving rejects to file kernel/sched/features.h.rej

**Pull request merged**
