### PR TITLE
Unify Ubuntu and Debian dependency installation

### PR DESCRIPTION
**Pull request by v1993**
My KUbuntu installation turned out to lack `libelf-dev`, causing build error. I originally wanted to simply add it to Ubuntu package list, but then noticed that Debian option already includes it.

Since there's no harm in trying to install already installed packages, I've just merged two codepaths to use Debian's more extensive package list.

### CODE REVIEW

**Comment by AdelKS** [comment]
If the dependencies are available in both distros with the same name, then yes it makes us win few lines of code, have you tested both distros ? Which distro did you try otherwise ? For example Fedora and Suse do not name _all_ their packages the same way.

**Comment by v1993** [comment]
I've tested it in Ubuntu, since list remains unchanged for Debian.

**Comment by AdelKS** [comment]
Awesome. Probably the Debian/Ubuntu differentiation is not needed any longer, I will have a look.

**Comment by Tk-Glitch** [comment]
Thanks! :frog: :heart:

**Pull request merged**
