### PR TITLE
Add bcachefs for 6.5

### PR DESCRIPTION
**Pull request by obj-obj**
Currently untested, this will remain a draft PR until I make sure nothing goes wrong

### CODE REVIEW

**Comment by ptr1337** [comment]
These patches are completly malformed, besides the bcachefs one from lucjan

**Comment by obj-obj** [comment]
> These patches are completly malformed, besides the bcachefs one from lucjan

Yeah, I'll have to fix it tomorrow

I got them directly from the linux-surface github, but I think something went wrong when I downloaded them

**Comment by simifor** [comment]
Haven't done a lot of testing, but bcachefs seems to work fine, I can read and write files as expected. I only grabbed that patch so I can't say anything about the other patches in this PR

**Comment by obj-obj** [comment]
Oh, it was already added anyway

**Pull request closed without merging**
