### PR TITLE
glitched-cfs-additions: fix for 6.5.2, remove performance-killing printk calls in bcachefs patches

### PR DESCRIPTION
**Pull request by Tatsh**
- The `printk` calls in `test_free`/`test_malloc` (called from `madvise`) were accidentally left in by the author and can randomly cause major performance problems even if none of the bcachefs options are enabled. They are triggered when `madvise` is called with `MADV_COLLAPSE`. Thousands of these messages attempt to get printed. `dmesg` seems to never stop printing. I was getting messages in journal:

```
Sep 10 23:27:39 limelight kernel: test_alloc invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_alloc invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_alloc invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_alloc invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_alloc invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_alloc invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_alloc invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_alloc invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_alloc invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_alloc invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_free invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_free invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_free invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_free invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_free invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_free invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_free invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_free invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_free invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_free invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_alloc invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_alloc invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_alloc invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_alloc invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_alloc invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight kernel: test_alloc invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight systemd-journald[707]: Missed 8175 kernel messages
Sep 10 23:27:39 limelight kernel: test_free invoked with args in1=824637915136 in2=4194304
Sep 10 23:27:39 limelight systemd-journald[707]: Missed 181 kernel messages
```

### CODE REVIEW

**Comment by ptr1337** [comment]
> Thanks Tatsh!
> 
> I'm not sure I follow the glitched-cfs-additions part. The patch applies fine, and I don't see changes upstream that would invalidate them. Would you be able to give more details?

I think he put it into the wrong folder. This will be required for 6.6 and its eevdf merge.

**Comment by Tatsh** [comment]
I'd be happy to make this PR just for removal of the printk calls.

Regarding glitched-cfs-additions, I pulled the latest version from the repo and it does not work to apply it to 6.5.2. From memory, the patch worked with 6.5.0 and maybe 6.5.1 (or the immediate prior version). That's what I intended to address here.

I am applying to the gentoo-sources source, which is a modified source (not by much) but I haven't seen any conflicts. Everything else in the repo here has applied cleanly.

I can't easily test 6.6 yet.

**Comment by Tatsh** [comment]
> That patch isn't applied when using eevdf (and cfs isn't a valid option on 6.6) so I prefer to ask.

So if I choose to use the eevdf patch, I should not apply cfs-additions?

**Comment by Tk-Glitch** [comment]
> > That patch isn't applied when using eevdf (and cfs isn't a valid option on 6.6) so I prefer to ask.
> 
> So if I choose to use the eevdf patch, I should not apply cfs-additions?

Indeed.

**Comment by Tatsh** [comment]
I updated the PR to just have the printk's removed.

**Comment by Tk-Glitch** [comment]
Alright! Thanks again Tatsh! :frog: :heart:

**Pull request merged**
