### PR TITLE
Add back #62 Add initial -rc support to the install.sh script.

### PR DESCRIPTION
**Pull request by Hyper-KVM**
This PR #62  was merged after starting the work on the unified build script.

Also add 5.10 RC to opt_ver case.

### CODE REVIEW

**Comment by Tk-Glitch** [comment]
Thank you! :frog: :heart:

**Comment by AdelKS** [comment]
Super! I will start working on unifying all the linux git folders into one and just `git chekout` between shallow branches. @Tk-Glitch what do you think of actually using the git folder instead of tarballs for Arch's build script ?

**Comment by Tk-Glitch** [comment]
I'm still against it as the default. I'd be okay with it as an optional path if it's not too invasive :frog: .

**Comment by AdelKS** [comment]
I will try to think of it. I keep on suggesting this because the downside of the tarballs is disk usage for SSDs: the kernel is decompressed every time `makepkg` is run right ?

**Comment by Tk-Glitch** [comment]
Yes I know :stuck_out_tongue: , but you can easily use a tmpfs to do that in RAM if you don't have a HDD or if you're worried about your SSD's lifespan. Makepkg has options for that. Of course if you don't have enough RAM for the task it's more involved :frog:

**Comment by Tk-Glitch** [comment]
Screenshot_20201027_201856
By the way, here's the tmpfs usage for a fresh 5.10rc1 build. A 4GB RAM equipped system would do just fine here, while building faster than on SSD, and without the disk writes.

**Comment by AdelKS** [comment]
I was about to actually ask you how much tmpfs is needed. 4GB that's little! I will set that up then. Does it have to be permanent, in the `fstab` ?

**Comment by Tk-Glitch** [comment]
Systemd will create a default tmpfs in /tmp with a size of half your total RAM if it doesn't exist in fstab. You can override that by adding an entry to your fstab to set it to whatever size you want. If you fill up your RAM completely for some reason, swap will then be used.

See https://wiki.archlinux.org/index.php/Tmpfs

**Comment by AdelKS** [comment]
Thanks for the information!

**Pull request merged**
