### PR TITLE
6.6: Fix For Fedora and OpenSuse

### PR DESCRIPTION
**Pull request by Virtuoz-Ier**

### CODE REVIEW

**Comment by Virtuoz-Ier** [comment]
Only tested on OpenSuse, but it should work for Fedora too.
@Nanotwerp if you can confirm it works on Fedora?

**Comment by Virtuoz-Ier** [comment]
Merged, and tested on OpenSuse.
Looks good to me!

**Comment by AdelKS** [comment]
Thanks guys for figuring things out, I will trust that these changes work out for you :P

**Comment by Exotic0015** [comment]
Seems to fix #822, but now nvidia drivers complain about a missing package called kernel-uname-r
```
Error: 
 Problem: conflicting requests
  - nothing provides kernel-uname-r = 6.6.1_tkg_bore needed by kmod-nvidia-6.6.1_tkg_bore-3:535.129.03-1.fc39.x86_64 from @commandline
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by AdelKS** [comment]
Ah thanks @Exotic0015, @Virtuoz-Ier please put back the kernel-devel-uname-r lines in the patch

**Comment by Virtuoz-Ier** [comment]
Done!

**Comment by Exotic0015** [comment]
Thanks, that seems to have fixed it 🎉

**Comment by Tk-Glitch** [comment]
Thanks guys! Merging time.
:frog: :heart:

**Pull request merged**
