### PR TITLE
Add custom LLVM compiler path support

### PR DESCRIPTION
**Pull request by Hyper-KVM**

### CODE REVIEW

**Comment by Tk-Glitch** [comment]
:frog:

**Comment by AdelKS** [comment]
@Hyper-KVM Were you able to use Google's LLVM LTO and PGO patches ?

**Comment by Hyper-KVM** [comment]
> @Hyper-KVM Were you able to use Google's LLVM LTO and PGO patches ?
I tried LTO but I seem to have a memory leak which makes it useless for me as it causes the system to lockup. I want to eventually get LTO support going too.

**Comment by AdelKS** [comment]
Oh I see, thanks for the feedback. Yea that would be awesome. Google had some hold statements about the improvements of LTO + PGO for their kernels, something like the Kernel taking 20% less cycles on the CPU

**Pull request merged**
