### PR TITLE
linux60: Fix Winesync patchset for 6.0-rc3

### PR DESCRIPTION
**Pull request by Iglu47**
small change for smooth applying

### CODE REVIEW

**Comment by Tk-Glitch** [comment]
Thanks! :frog: :heart:

**Comment by compicat** [comment]
can somebody confirm winesync is working with newer wine versions than 6.10 which had been hold?

**Comment by Iglu47** [comment]
> can somebody confirm winesync is working with newer wine versions than 6.10 which had been hold?

no, previous versions of fastsync is deprecated and should be avoided, 4 version of winesync and fastsync are currently relevant:
- all current patches in linux-tkg provide 4 version of winesync
- on wine-tkg side, patches are available only for ~7.7+. To support lower versions of Wine, need additionally to backport the actual version of fastsync (which would be a non-trivial task).

**Comment by compicat** [comment]
sorry for thanking late. I should at least say that, winesync is better than futex_wait even it is very little to scale, thanks for this fix and all for your help.

**Pull request merged**
