### PR TITLE
5.16.0

### PR DESCRIPTION
**Pull request by Snoop05**

### CODE REVIEW

**Review by gardotd426 — APPROVED** [review]
Yeah I was doing this same thing to file the PR before I saw you'd beat me to it, same exact changes here, kernel built successfully

**Comment by drishal** [comment]
5.16.1 is now out tbh

**Comment by netbospl** [comment]
> 5.16.1 is now out tbh

Have a look at my pull request #391

**Comment by Snoop05** [comment]
closing in favor of #401

**Pull request closed without merging**
