### PR TITLE
Kernel versions update

### PR DESCRIPTION
**Pull request by netbospl**

### CODE REVIEW

**Comment by ninelore** [comment]
Just built 5.15.12 with this without issues

**Comment by ninelore** [comment]
5.15.13 is out https://lkml.org/lkml/2022/1/5/403

**Comment by netbospl** [comment]
@ninelore True, next commit 288970a1776374100d9bd8e1aa7cc1e80de90662 updates script further

**Comment by ninelore** [comment]
saw it ty

5.15.13 built and runs fine btw

**Comment by netbospl** [comment]
Currently building 5.16.1 on this script, slight shame that cacule is not supported on this version, CFS will have to do :(

**Comment by Tk-Glitch** [comment]
Thank you @netbospl and @devacom

**Pull request merged**
