### PR TITLE
Debian UEFI cert compile problem

### PR DESCRIPTION
**Pull request by iWeaker4you**

### CODE REVIEW

**Comment by AdelKS** [comment]
Hello! I am not a `sed` expert so I want to confirm with, are you basically emptying `CONFIG_SYSTEM_TRUSTED_KEYS`, aka setting it to `CONFIG_SYSTEM_TRUSTED_KEYS=""` ? I need to understand that because I will open a PR soon where all the `sed` commands will be replaced with a script from the linux source code itself, meant to edit the `.config` file in a more human readable way.

**Comment by Tk-Glitch** [comment]
Thank you! This should fix https://github.com/Frogging-Family/linux-tkg/issues/115

**Comment by Tk-Glitch** [comment]
@AdelKS This will need exceptions depending on kernel version/commit id to handle failures (which isn't an issue with sed), which will make it even more annoying to read imho.

**Comment by AdelKS** [comment]
Then forget about it x) @Tk-Glitch

**Pull request merged**
