### PR TITLE
Updates for rc8 for kernel 5.9

### PR DESCRIPTION
**Pull request by Doctorwho1909**
Tested and working when building
image

### CODE REVIEW

**Comment by Doctorwho1909** [comment]
Either a bug or something else needs updating 
```
make[2]: *** [scripts/Makefile.build:283: fs/nfs/nfs4sysctl.o] Error 1
make[2]: *** Waiting for unfinished jobs....
  CC [M]  net/ipv6/tunnel6.o
  CC [M]  net/ipv4/ipcomp.o
  CC [M]  net/ipv4/xfrm4_tunnel.o
  CC [M]  net/ipv4/tunnel4.o
  CC [M]  net/ipv4/inet_diag.o
  CC [M]  net/ipv6/mip6.o
  CC [M]  net/ipv6/ip6_vti.o
  CC [M]  net/ipv6/sit.o
  CC [M]  net/ipv6/ip6_tunnel.o
  CC [M]  net/ipv4/tcp_diag.o
  CC [M]  net/ipv4/udp_diag.o
  CC [M]  net/ipv6/ip6_gre.o
  CC [M]  net/ipv6/fou6.o
  CC [M]  net/ipv6/ip6_udp_tunnel.o
  CC [M]  net/ipv4/raw_diag.o
  AR      net/ipv6/built-in.a
  CC [M]  net/ipv4/tcp_bbr.o
  CC [M]  net/ipv4/tcp_bic.o
  CC [M]  net/ipv4/tcp_cdg.o
  CC [M]  net/ipv4/tcp_dctcp.o
  CC [M]  net/ipv4/tcp_westwood.o
  CC [M]  net/ipv4/tcp_highspeed.o
  CC [M]  net/ipv4/tcp_hybla.o
  CC [M]  net/ipv4/tcp_htcp.o
  CC [M]  net/ipv4/tcp_vegas.o
  CC [M]  net/ipv4/tcp_nv.o
  CC [M]  net/ipv4/tcp_veno.o
  CC [M]  net/ipv4/tcp_scalable.o
  CC [M]  net/ipv4/tcp_lp.o
  CC [M]  net/ipv4/tcp_yeah.o
  CC [M]  net/ipv4/tcp_illinois.o
make[1]: *** [scripts/Makefile.build:500: fs/nfs] Error 2
make: *** [Makefile:1784: fs] Error 2
  LD [M]  net/ipv4/gre.o
  LD [M]  net/ipv4/udp_tunnel.o
  AR      net/ipv4/built-in.a
make: *** [Makefile:1784: net] Error 2
==> ERROR: A failure occurred in build().

```

**Comment by Doctorwho1909** [comment]
closing not sure how to fix scripts like that sorry

**Comment by Tk-Glitch** [comment]
I haven't hit an issue building RC8 myself, and decided to push https://github.com/Frogging-Family/linux-tkg/commit/d7918fc63bd3f087a2ea11aa51db276ae5b6210f

**Comment by Doctorwho1909** [comment]
> I haven't hit an issue building RC8 myself, and decided to push [d7918fc](https://github.com/Frogging-Family/linux-tkg/commit/d7918fc63bd3f087a2ea11aa51db276ae5b6210f)

i will try again

**Pull request closed without merging**
